version: "3"
services:
  client:
    image: client
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - menu
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  server:
    image: server
    build: ./server/
    ports:
      - "8080:8080"
    networks:
      - menu
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    command: yarn start:dev
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - menu
    ports:
      - 27017:27017

networks:
  menu:
    driver: bridge
volumes:
  mongo-data:
    driver: local
