name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: yarn install
      - name: Test app
        run: yarn typecheck
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: yarn
      - name: Lint code
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: yarn
      - name: Build App
        run: |
          yarn build
          echo "Hello"
